// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package databaseModels

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type studentsTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *studentsTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("students").
func (v *studentsTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *studentsTableType) Columns() []string {
	return []string{
		"id",
		"name",
		"vk_link",
		"student_group",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *studentsTableType) NewStruct() reform.Struct {
	return new(Students)
}

// NewRecord makes a new record for that table.
func (v *studentsTableType) NewRecord() reform.Record {
	return new(Students)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *studentsTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// StudentsTable represents students view or table in SQL database.
var StudentsTable = &studentsTableType{
	s: parse.StructInfo{
		Type:    "Students",
		SQLName: "students",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int32", Column: "id"},
			{Name: "Name", Type: "string", Column: "name"},
			{Name: "VkLink", Type: "*string", Column: "vk_link"},
			{Name: "StudentGroup", Type: "string", Column: "student_group"},
		},
		PKFieldIndex: 0,
	},
	z: new(Students).Values(),
}

// String returns a string representation of this struct or record.
func (s Students) String() string {
	res := make([]string, 4)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Name: " + reform.Inspect(s.Name, true)
	res[2] = "VkLink: " + reform.Inspect(s.VkLink, true)
	res[3] = "StudentGroup: " + reform.Inspect(s.StudentGroup, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Students) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Name,
		s.VkLink,
		s.StudentGroup,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Students) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Name,
		&s.VkLink,
		&s.StudentGroup,
	}
}

// View returns View object for that struct.
func (s *Students) View() reform.View {
	return StudentsTable
}

// Table returns Table object for that record.
func (s *Students) Table() reform.Table {
	return StudentsTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Students) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Students) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Students) HasPK() bool {
	return s.ID != StudentsTable.z[StudentsTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *Students) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = StudentsTable
	_ reform.Struct = (*Students)(nil)
	_ reform.Table  = StudentsTable
	_ reform.Record = (*Students)(nil)
	_ fmt.Stringer  = (*Students)(nil)
)

func init() {
	parse.AssertUpToDate(&StudentsTable.s, new(Students))
}
